//! RT 求交吞吐基准 SPIR-V 手工汇编器（干净版：确定性 ID + 全部官方修正）
//! 修正：composite=44, init=4473, proceed=4477, gettype=4479, convert=4447;
//! gid BuiltIn=28; 入口名 LE; 存储类; 循环 latch; 块收尾分支; bound; caps(Shader/RayQueryKHR/RayTracingKHR)

pub fn rt_bench_spv() -> Vec<u32> {
    let mut w: Vec<u32> = vec![];
    let mut defs: Vec<(u32, Vec<u32>)> = vec![];
    let mut i = 0u32;
    let mut newid = |i: &mut u32| { *i += 1; *i };
    let t_void = newid(&mut i);
    let t_fn = newid(&mut i);
    let t_bool = newid(&mut i);
    let t_u32 = newid(&mut i);
    let t_f32 = newid(&mut i);
    let t_u64 = newid(&mut i);
    let t_v3u = newid(&mut i);
    let t_v3f = newid(&mut i);
    let t_accel = newid(&mut i);
    let t_p_sb_u64 = newid(&mut i);
    let t_p_sb_u32 = newid(&mut i);
    let t_p_in_v3u = newid(&mut i);
    let t_rq = newid(&mut i);
    let t_p_f_rq = newid(&mut i);
    let t_arr_u32 = newid(&mut i);
    let t_arr_u64 = newid(&mut i);
    let t_struct_hits = newid(&mut i);
    let t_struct_addr = newid(&mut i);
    let c0 = newid(&mut i);
    let c255 = newid(&mut i);
    let c0f = newid(&mut i);
    let c001f = newid(&mut i);
    let c1000f = newid(&mut i);
    let c1 = newid(&mut i);
    let c1024 = newid(&mut i);
    let vzero = newid(&mut i);
    let g_tlas = newid(&mut i);
    let g_hits = newid(&mut i);
    let g_gid = newid(&mut i);
    let f_main = newid(&mut i);
    let l_entry = newid(&mut i);
    let l_loop = newid(&mut i);
    let l_latch = newid(&mut i);
    let l_merge = newid(&mut i);
    let l_hit = newid(&mut i);
    let l_skip = newid(&mut i);
    let rq = newid(&mut i);
    let gv = newid(&mut i);
    let gx = newid(&mut i);
    let gy = newid(&mut i);
    let fx = newid(&mut i);
    let fy = newid(&mut i);
    let dir = newid(&mut i);
    let tl_addr = newid(&mut i);
    let tl = newid(&mut i);
    let cont = newid(&mut i);
    let ityp = newid(&mut i);
    let ishit = newid(&mut i);
    let hit_ptr = newid(&mut i);
    defs.push((17, vec![1]));
    defs.push((17, vec![4472]));
    defs.push((17, vec![4479]));
    defs.push((14, vec![0, 1]));
    defs.push((15, vec![5, f_main, 0x6e69_616d, g_gid]));
    defs.push((16, vec![f_main, 17, 64, 1, 1]));
    defs.push((71, vec![g_tlas, 34, 0]));
    defs.push((71, vec![g_tlas, 33, 0]));
    defs.push((71, vec![g_hits, 34, 0]));
    defs.push((71, vec![g_hits, 33, 1]));
    defs.push((71, vec![g_gid, 11, 28]));
    defs.push((19, vec![t_void]));
    defs.push((33, vec![t_fn, t_void]));
    defs.push((20, vec![t_bool]));
    defs.push((21, vec![t_u32, 32, 0]));
    defs.push((22, vec![t_f32, 32]));
    defs.push((21, vec![t_u64, 64, 0]));
    defs.push((23, vec![t_v3u, t_u32, 3]));
    defs.push((23, vec![t_v3f, t_f32, 3]));
    defs.push((5341, vec![t_accel]));
    defs.push((43, vec![c1024, t_u32, 1024]));
    defs.push((28, vec![t_arr_u64, t_u64, c1024]));
    defs.push((28, vec![t_arr_u32, t_u32, c1024]));
    defs.push((30, vec![t_struct_addr, t_arr_u64]));
    defs.push((30, vec![t_struct_hits, t_arr_u32]));
    defs.push((72, vec![t_struct_addr, 0, 35, 0]));
    defs.push((72, vec![t_struct_hits, 0, 35, 0]));
    defs.push((72, vec![t_struct_addr, 0, 6, 8]));
    defs.push((72, vec![t_struct_hits, 0, 6, 4]));
    defs.push((71, vec![t_struct_addr, 2]));
    defs.push((71, vec![t_struct_hits, 2]));
    defs.push((32, vec![t_p_sb_u64, 12, t_struct_addr]));
    defs.push((32, vec![t_p_sb_u32, 12, t_struct_hits]));
    defs.push((32, vec![t_p_in_v3u, 1, t_v3u]));
    defs.push((4472, vec![t_rq]));
    defs.push((32, vec![t_p_f_rq, 7, t_rq]));
    defs.push((43, vec![c0, t_u32, 0]));
    defs.push((43, vec![c255, t_u32, 255]));
    defs.push((43, vec![c0f, t_f32, 0]));
    defs.push((43, vec![c001f, t_f32, 0x3a83126f]));
    defs.push((43, vec![c1000f, t_f32, 0x447a0000]));
    defs.push((43, vec![c1, t_u32, 1]));
    defs.push((44, vec![vzero, t_v3f, c0f, c0f, c0f]));
    defs.push((59, vec![g_tlas, t_p_sb_u64, 12]));
    defs.push((59, vec![g_hits, t_p_sb_u32, 12]));
    defs.push((59, vec![g_gid, t_p_in_v3u, 1]));
    defs.push((54, vec![f_main, t_void, 0, t_fn]));
    defs.push((248, vec![l_entry]));
    defs.push((59, vec![rq, t_p_f_rq, 7]));
    defs.push((61, vec![gv, t_v3u, g_gid]));
    defs.push((186, vec![gx, t_u32, gv, 0]));
    defs.push((186, vec![gy, t_u32, gv, 1]));
    defs.push((111, vec![fx, t_f32, gx]));
    defs.push((111, vec![fy, t_f32, gy]));
    defs.push((80, vec![dir, t_v3f, fx, fy, c001f]));
    defs.push((61, vec![tl_addr, t_u64, g_tlas]));
    defs.push((4447, vec![tl, t_accel, tl_addr]));
    defs.push((4473, vec![rq, tl, c0, c255, vzero, c001f, dir, c1000f]));
    defs.push((249, vec![l_loop]));
    defs.push((248, vec![l_loop]));
    defs.push((246, vec![l_merge, l_latch, 0]));
    defs.push((4477, vec![cont, t_bool, rq]));
    defs.push((250, vec![cont, l_latch, l_merge]));
    defs.push((248, vec![l_latch]));
    defs.push((249, vec![l_loop]));
    defs.push((248, vec![l_merge]));
    defs.push((4479, vec![ityp, t_u32, rq, c0]));
    defs.push((171, vec![ishit, t_bool, ityp, c0]));
    defs.push((250, vec![ishit, l_hit, l_skip]));
    defs.push((248, vec![l_hit]));
    defs.push((65, vec![hit_ptr, t_p_sb_u32, g_hits, c0, gx]));
    defs.push((62, vec![hit_ptr, c1]));
    defs.push((249, vec![l_skip]));
    defs.push((248, vec![l_skip]));
    defs.push((253, vec![]));
    defs.push((56, vec![]));
    w.push(0x0723_0203u32);
    w.push(0x0001_0600u32);
    w.push(0u32);
    w.push(i + 1);
    w.push(0u32);
    for (op, ops) in &defs {
        w.push(((1 + ops.len()) as u32) << 16 | op);
        w.extend_from_slice(ops);
    }
    w
}
